spring.application.name=LPM_APP2
spring.datasource.url=jdbc:postgresql://localhost:5432/lpm_db
spring.datasource.username=postgres
spring.datasource.password=Jeep1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
springdoc.swagger-ui.path=/swagger-ui.html